name: Markdown lint (project files)

on:
  pull_request:
    branches:
      - main
      - eslint-config-gh-action # for testing only
    paths:
      - '*.md'
      - .github/workflows/markdown-lint.yml


jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Lint markdown files
        run: |
          npx markdownlint-cli '*.md' -i LICENSE.md -i CODE_OF_CONDUCT.md
          
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24
        with:
          separator: " "
          files: |
            files/en-us/web/api/**/*.md
          

      - name: List all changed files
        run: |
          npx eslint ${{ steps.changed-files.outputs.all_changed_files }} --format stylish
